<?php
namespace App\Services;

final class DemoContent {
    public static function services(): array {return [
        ['id'=>1,'title'=>'eBook Writing & Ghostwriting','slug'=>'ebook-writing','summary'=>'Turn a promising idea into a clear, compelling manuscript.','description'=>'We help authors develop an idea, establish a strong voice and complete a polished manuscript.','benefits'=>"Voice-led collaboration\nClear chapter milestones\nEditorial direction",'timeline'=>'8-16 weeks','starting_price'=>1500,'display_order'=>1,'is_active'=>1],
        ['id'=>2,'title'=>'Editing & Proofreading','slug'=>'editing-proofreading','summary'=>'Give your manuscript the precision and polish it deserves.','description'=>'Developmental, line and proof editing shaped around your manuscript and audience.','benefits'=>"Experienced editorial eye\nActionable feedback\nPublication-ready copy",'timeline'=>'2-8 weeks','starting_price'=>500,'display_order'=>2,'is_active'=>1],
        ['id'=>3,'title'=>'Book Cover Design','slug'=>'book-cover-design','summary'=>'A cover that introduces your book with clarity and character.','description'=>'Original concepts positioned for your genre and your eBook readers.','benefits'=>"Original concepts\nDigital-ready files\nStrategic genre positioning",'timeline'=>'2-4 weeks','starting_price'=>350,'display_order'=>3,'is_active'=>1],
        ['id'=>4,'title'=>'eBook Formatting','slug'=>'ebook-formatting','summary'=>'Beautiful, reliable files for every reader and device.','description'=>'Thoughtful digital typesetting for EPUB and accessible PDF delivery.','benefits'=>"EPUB and PDF files\nDevice tested\nAccessible structure",'timeline'=>'1-2 weeks','starting_price'=>250,'display_order'=>4,'is_active'=>1],
        ['id'=>5,'title'=>'Publishing Assistance','slug'=>'publishing-assistance','summary'=>'A clear route through the decisions that follow a finished manuscript.','description'=>'Practical support for ISBNs, metadata, distribution and release planning.','benefits'=>"Practical roadmap\nMetadata setup\nRelease planning",'timeline'=>'4-6 weeks','starting_price'=>750,'display_order'=>5,'is_active'=>1],
        ['id'=>6,'title'=>'Author Website Development','slug'=>'author-websites','summary'=>'An elegant home for your books, biography and readers.','description'=>'A lightweight author website designed to make discovery easy.','benefits'=>"Mobile ready\nReader-focused\nEasy handover",'timeline'=>'3-6 weeks','starting_price'=>900,'display_order'=>6,'is_active'=>1],
        ['id'=>7,'title'=>'Book Marketing','slug'=>'book-marketing','summary'=>'A focused campaign built for your particular readership.','description'=>'A considered marketing plan rather than noise for its own sake.','benefits'=>"Audience research\nLaunch strategy\nClear priorities",'timeline'=>'4-10 weeks','starting_price'=>600,'display_order'=>7,'is_active'=>1],
        ['id'=>8,'title'=>'Audiobook Production','slug'=>'audiobook-production','summary'=>'Turn your book into an intimate listening experience.','description'=>'End-to-end audiobook production with narration support and finished masters.','benefits'=>"Narrator matching\nClean mastering\nPlatform-ready files",'timeline'=>'6-12 weeks','starting_price'=>1200,'display_order'=>8,'is_active'=>1],
    ];}
    public static function authors(): array {return [['name'=>'Mara Ellison','slug'=>'mara-ellison','bio'=>'A writer of luminous literary fiction, Mara follows the quiet pressure of a life changing course.','tagline'=>'Fiction and essays','website'=>''],['name'=>'Jonas Vale','slug'=>'jonas-vale','bio'=>'Jonas writes considered essays on art, attention and the natural world.','tagline'=>'Essays and culture','website'=>''],['name'=>'Imani Reed','slug'=>'imani-reed','bio'=>'Imani is a poet and teacher interested in memory, city and home.','tagline'=>'Poetry','website'=>''],['name'=>'Theo March','slug'=>'theo-march','bio'=>'Theo writes narrative non-fiction with curiosity and warmth.','tagline'=>'Non-fiction','website'=>'']];}
    public static function posts(): array {return [['title'=>'How to Finish a First Draft Without Losing Its Pulse','slug'=>'finish-a-first-draft','excerpt'=>'A first draft does not need to be elegant. It needs to remain alive long enough for you to discover what it wants to become.','body'=>'Finishing a draft is an act of sustained attention, not a test of confidence. Set a small, repeatable appointment with the work. Let the early pages be imperfect. Keep a separate notebook for doubts and return to the manuscript itself.','published_at'=>'2026-01-15 09:00:00'],['title'=>'What a Good Editor Actually Does','slug'=>'what-a-good-editor-does','excerpt'=>'The best editing is rigorous, specific and deeply respectful of an author’s intention.','body'=>'An editor does not replace the writer. They make the work more visible to itself. Developmental editing looks at structure; line editing listens to language; proofreading attends to final details.','published_at'=>'2026-02-04 09:00:00'],['title'=>'A Thoughtful Way to Plan Your Book Launch','slug'=>'thoughtful-book-launch','excerpt'=>'A book launch need not be loud to be meaningful. Start by deciding who needs this book most.','body'=>'Begin with the readers closest to the work. Create a simple release calendar. Share the story behind the book, not only the book itself.','published_at'=>'2026-03-01 09:00:00']];}
    public static function testimonials(): array {return [['name'=>'Aisha N.','role'=>'First-time author','quote'=>'Archon gave my manuscript both conviction and care. The whole process felt clear and collaborative.'],['name'=>'M. Carter','role'=>'Essayist','quote'=>'The editorial feedback was specific, generous and immediately useful.'],['name'=>'Leah D.','role'=>'Novelist','quote'=>'Every decision made the book feel more like itself.'],['name'=>'R. Stone','role'=>'Founder','quote'=>'An unusually thoughtful publishing partner from first draft through release.']];}
    public static function faqs(string $title): array {return [['question'=>'Is '.$title.' tailored to my project?','answer'=>'Yes. We begin with a conversation about your manuscript, goals, audience and preferred timeline before recommending a clear scope.'],['question'=>'How will we work together?','answer'=>'You receive an agreed schedule, straightforward milestones and a single point of contact throughout the work.'],['question'=>'Can I combine this with another service?','answer'=>'Absolutely. Many authors combine this service with editing, cover design, formatting or publishing guidance.']];}
}
