<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';

use App\Core\Database;
$db=Database::pdo();
$adminEmail=getenv('SEED_ADMIN_EMAIL')?:'admin@archon.test';$adminPassword=getenv('SEED_ADMIN_PASSWORD');if(!$adminPassword){fwrite(STDERR,"Set SEED_ADMIN_PASSWORD before seeding.\n");exit(1);} $db->beginTransaction();
try{
 $db->exec("INSERT INTO roles(name) VALUES ('super_admin'),('editor')");$db->prepare('INSERT INTO admins(name,email,password_hash) VALUES(?,?,?)')->execute(['Development Administrator',$adminEmail,password_hash($adminPassword,PASSWORD_DEFAULT)]);$admin=(int)$db->lastInsertId();$db->prepare('INSERT INTO admin_roles(admin_id,role_id) VALUES(?,1)')->execute([$admin]);
 $db->prepare('INSERT INTO customers(name,email,password_hash) VALUES(?,?,?)')->execute(['Demo Reader','reader@archon.test',password_hash('Reader12345',PASSWORD_DEFAULT)]);
 $authors=[['Mara Ellison','mara-ellison','A writer of luminous literary fiction, Mara follows the quiet pressure of a life changing course.','Fiction & essays'],['Jonas Vale','jonas-vale','Jonas writes considered essays on art, attention and the natural world.','Essays & culture'],['Imani Reed','imani-reed','Imani is a poet and teacher interested in memory, city and home.','Poetry'],['Theo March','theo-march','Theo’s narrative non-fiction is rigorous, curious and warm.','Non-fiction'],['Elena Shore','elena-shore','Elena writes bright, intimate books about creativity and work.','Creative practice']];$q=$db->prepare('INSERT INTO authors(name,slug,bio,tagline,is_featured) VALUES(?,?,?,?,1)');foreach($authors as $a)$q->execute($a);
 $categories=[['Fiction','fiction'],['Poetry','poetry'],['Essays','essays'],['Creative Living','creative-living'],['History','history']];$q=$db->prepare('INSERT INTO categories(name,slug) VALUES(?,?)');foreach($categories as $r)$q->execute($r);$genres=[['Literary Fiction','literary-fiction'],['Memoir','memoir'],['Craft','craft'],['Culture','culture']];$q=$db->prepare('INSERT INTO genres(name,slug) VALUES(?,?)');foreach($genres as $r)$q->execute($r);
 $books=[['A Quiet Longitude','a-quiet-longitude',1,'9780000000011','A delicate novel about starting again.','On an island where time feels both held and urgent, one woman learns to read the shape of a future she never planned.',12.99,9.99,1],['The Art of Begins','the-art-of-begins',5,'9780000000028','A practical companion for creative momentum.','A gentle, exacting invitation to begin imperfectly and continue with purpose.',10.99,null,1],['Paper Cities','paper-cities',3,'9780000000035','Poems for the streets we remember.','Poems that map the city through friendship, weather and the architecture of memory.',8.99,null,0],['The Patient Editor','the-patient-editor',2,'9780000000042','Essays on clear writing and slow reading.','A collection of essays about the merciful work of revision and attentive reading.',11.99,8.99,1],['The Listening Field','the-listening-field',4,'9780000000059','A nature writer reconsiders attention.','A field notebook of walks, research and small discoveries in a changing landscape.',13.99,null,0],['Small Bright Work','small-bright-work',5,'9780000000066','Making a creative life that lasts.','A compassionate guide to building creative rituals spacious enough for real life.',9.99,null,0],['The Mapmaker’s Window','the-mapmakers-window',1,'9780000000073','A story of maps, kinship and distance.','A family archive uncovers a map that changes how a daughter understands her origins.',14.99,11.99,1],['After the Margin','after-the-margin',2,'9780000000080','New essays on books and belonging.','Thoughtful essays from a lifelong reader at the edges of the literary world.',10.99,null,0]];
 $q=$db->prepare('INSERT INTO books(title,slug,author_id,isbn,short_description,description,price,sale_price,is_featured,published_at,page_count,rating,sales_count) VALUES(?,?,?,?,?,?,?,?,?,CURDATE(),220,4.7,20)');foreach($books as $b){$q->execute($b);$id=(int)$db->lastInsertId();$db->prepare('INSERT INTO book_categories(book_id,category_id) VALUES(?,?)')->execute([$id,(($id-1)%5)+1]);$db->prepare('INSERT INTO book_genres(book_id,genre_id) VALUES(?,?)')->execute([$id,(($id-1)%4)+1]);}
 $services=[['eBook Writing & Ghostwriting','ebook-writing','Bring an unfinished idea into a confident, readable manuscript.','We pair your voice with an experienced writer and a transparent developmental process.','Voice-led collaboration\nClear chapter milestones\nEditorial direction','8–16 weeks',1500,1],['Editing & Proofreading','editing-proofreading','Give your manuscript the precision and polish it deserves.','Developmental, line and proof editing tailored to the work at hand.','Experienced editorial eye\nActionable feedback\nPublication-ready copy','2–8 weeks',500,2],['Book Cover Design','book-cover-design','A cover that introduces your book with clarity and character.','Original cover concepts shaped around audience, genre and your book’s distinct voice.','Original concepts\nPrint and digital files\nStrategic genre positioning','2–4 weeks',350,3],['eBook Formatting','ebook-formatting','Beautiful, reliable files for every reader and device.','Thoughtful digital typesetting for EPUB and accessible PDF delivery.','EPUB and PDF files\nDevice tested\nAccessible structure','1–2 weeks',250,4],['Publishing Assistance','publishing-assistance','A clear route through the decisions that follow a finished manuscript.','Practical support for ISBNs, metadata, distribution and release planning.','Practical roadmap\nMetadata setup\nRelease planning','4–6 weeks',750,5],['Author Website Development','author-websites','An elegant home for your books, biography and readers.','A lightweight author website designed to make discovery easy.','Mobile ready\nReader-focused\nEasy handover','3–6 weeks',900,6],['Book Marketing','book-marketing','A focused campaign built for your particular readership.','A considered marketing plan rather than noise for its own sake.','Audience research\nLaunch strategy\nClear priorities','4–10 weeks',600,7],['Audiobook Production','audiobook-production','Turn your book into an intimate listening experience.','End-to-end audiobook production with narration support and finished masters.','Narrator matching\nClean mastering\nPlatform-ready files','6–12 weeks',1200,8]];$q=$db->prepare('INSERT INTO services(title,slug,summary,description,benefits,timeline,starting_price,display_order) VALUES(?,?,?,?,?,?,?,?)');foreach($services as $s)$q->execute($s);
 $posts=[['How to Finish a First Draft Without Losing Its Pulse','finish-a-first-draft','A first draft does not need to be elegant. It needs to remain alive long enough for you to discover what it wants to become.','Finishing a draft is an act of sustained attention, not a test of confidence. Set a small, repeatable appointment with the work. Let the early pages be imperfect. Keep a separate notebook for doubts and return to the manuscript itself.\n\nWhen you reach the end, take a little distance before revising. A rested reader can see the book’s true structure more clearly.','published'],['What a Good Editor Actually Does','what-a-good-editor-does','The best editing is rigorous, specific and deeply respectful of an author’s intention.','An editor does not replace the writer. They make the work more visible to itself. Developmental editing looks at structure; line editing listens to language; proofreading attends to the final details.\n\nGood feedback is concrete enough to use and generous enough to keep a writer working.','published'],['A Thoughtful Way to Plan Your Book Launch','thoughtful-book-launch','A book launch need not be loud to be meaningful. Start by deciding who needs this book most.','Begin with the readers closest to the work. Create a simple release calendar. Share the story behind the book, not only the book itself. A considered launch has room for conversation and continuation.','published']];$q=$db->prepare('INSERT INTO blog_posts(title,slug,excerpt,body,status,published_at) VALUES(?,?,?,?,?,NOW())');foreach($posts as $p)$q->execute($p);
 $testimonials=[['Aisha N.','Author','Archon gave my manuscript both conviction and care.'],['M. Carter','Essayist','The process was calm, clear and beautifully organised.'],['Leah D.','Novelist','Every editorial decision made the book more itself.'],['R. Stone','Founder','An unusually thoughtful publishing partner.']];$q=$db->prepare('INSERT INTO testimonials(name,role,quote) VALUES(?,?,?)');foreach($testimonials as $t)$q->execute($t);$db->exec("INSERT INTO coupons(code,discount_type,discount_value,is_active) VALUES ('WELCOME10','percent',10,1),('ARCHON5','fixed',5,1)");$settings=['announcement.text'=>'Complimentary consultation for new publishing projects','announcement.link_label'=>'Request yours','home.hero.eyebrow'=>'INDEPENDENT PUBLISHING, REFINED','home.hero.title'=>'Turn your eBook idea into a professionally published story.','home.hero.body'=>'Archon helps authors shape, edit, design and publish remarkable eBooks with expert guidance at every stage.','home.hero.shop_label'=>'Explore services','home.hero.quote_label'=>'Request a consultation'];$q=$db->prepare('INSERT INTO settings(setting_key,setting_value) VALUES(?,?)');foreach($settings as $key=>$value)$q->execute([$key,$value]);
 $db->commit();echo "Seeded Archon demo data. Admin: $adminEmail\n";
}catch(Throwable $e){$db->rollBack();throw $e;}
