<?php
namespace App\Controllers;
use App\Core\Security;

final class AccountController extends Controller {
    public function dashboard(): never {$customer=$this->requireCustomer();$orders=$this->all('SELECT * FROM orders WHERE customer_id=? ORDER BY created_at DESC',[$customer['id']]);$downloads=$this->all('SELECT d.*,oi.title FROM downloads d JOIN order_items oi ON oi.id=d.order_item_id WHERE d.customer_id=? ORDER BY d.created_at DESC',[$customer['id']]);$reviews=$this->all('SELECT r.*,b.title,b.slug FROM reviews r JOIN books b ON b.id=r.book_id WHERE r.customer_id=? ORDER BY r.updated_at DESC',[$customer['id']]);$this->render('account/dashboard',compact('customer','orders','downloads','reviews'));}
    public function wishlist(): never {$customer=$this->requireCustomer();$books=$this->all('SELECT b.*,a.name author_name FROM wishlists w JOIN books b ON b.id=w.book_id JOIN authors a ON a.id=b.author_id WHERE w.customer_id=?',[$customer['id']]);$this->render('account/wishlist',compact('books'));}
    public function profile(): never {$customer=$this->requireCustomer();$record=$this->one('SELECT id,name,email,created_at FROM customers WHERE id=?',[$customer['id']]);$this->render('account/profile',compact('record'));}
    public function saveProfile(): never {$this->requirePost();$customer=$this->requireCustomer();$name=trim($_POST['name']??'');$email=filter_var($_POST['email']??'',FILTER_VALIDATE_EMAIL);if(strlen($name)<2||!$email){Security::flash('error','Enter a valid name and email address.');Security::redirect('/account/profile');}try{$this->db()->prepare('UPDATE customers SET name=?,email=? WHERE id=?')->execute([$name,$email,$customer['id']]);}catch(\PDOException){Security::flash('error','That email address is already in use.');Security::redirect('/account/profile');}$_SESSION['customer']['name']=$name;$_SESSION['customer']['email']=$email;Security::flash('success','Your profile has been updated.');Security::redirect('/account/profile');}
    public function changePassword(): never {$this->requirePost();$customer=$this->requireCustomer();$current=$_POST['current_password']??'';$new=$_POST['new_password']??'';$record=$this->one('SELECT password_hash FROM customers WHERE id=?',[$customer['id']]);if(!$record||!password_verify($current,$record['password_hash'])||strlen($new)<10||!preg_match('/[A-Za-z]/',$new)||!preg_match('/\d/',$new)){Security::flash('error','Check your current password. New passwords need 10 characters with letters and numbers.');Security::redirect('/account/profile');}$this->db()->prepare('UPDATE customers SET password_hash=? WHERE id=?')->execute([password_hash($new,PASSWORD_DEFAULT),$customer['id']]);session_regenerate_id(true);Security::flash('success','Your password has been changed.');Security::redirect('/account/profile');}
    public function toggleWishlist(): never {$this->requirePost();$c=$this->requireCustomer();$id=(int)($_POST['book_id']??0);$exists=$this->one('SELECT id FROM wishlists WHERE customer_id=? AND book_id=?',[$c['id'],$id]);if($exists)$this->db()->prepare('DELETE FROM wishlists WHERE id=?')->execute([$exists['id']]);else $this->db()->prepare('INSERT IGNORE INTO wishlists(customer_id,book_id) VALUES(?,?)')->execute([$c['id'],$id]);Security::flash('success',$exists?'Removed from your reading list.':'Added to your reading list.');Security::redirect($_POST['return_to']??'/account/wishlist');}
    public function download(string $token): never {$c=$this->requireCustomer();$download=$this->one('SELECT d.*,bf.storage_name,bf.original_name FROM downloads d JOIN order_items oi ON oi.id=d.order_item_id JOIN book_files bf ON bf.book_id=oi.book_id WHERE d.token=? AND d.customer_id=?',[$token,$c['id']]);if(!$download||strtotime($download['expires_at'])<time()||$download['download_count']>=$download['max_count']){$this->render('errors/404',[],404);} $path=dirname(__DIR__,2).'/private/books/'.$download['storage_name'];if(!is_file($path)){Security::flash('error','This development eBook file has not yet been uploaded.');Security::redirect('/account');}$this->db()->prepare('UPDATE downloads SET download_count=download_count+1,last_downloaded_at=NOW() WHERE id=?')->execute([$download['id']]);header('Content-Type: application/octet-stream');header('Content-Disposition: attachment; filename="'.str_replace('"','',$download['original_name']).'"');header('Content-Length: '.filesize($path));readfile($path);exit;}
}
