<?php
namespace App\Controllers;
use App\Core\Security;

final class AdminController extends Controller {
    private array $resources=['books'=>['table'=>'books','title'=>'eBooks','fields'=>['title','slug','author_id','price','sale_price','isbn','short_description','description','published_at','is_active','is_featured']], 'authors'=>['table'=>'authors','title'=>'Authors','fields'=>['name','slug','bio','website','is_active','is_featured']], 'services'=>['table'=>'services','title'=>'Services','fields'=>['title','slug','summary','description','benefits','timeline','starting_price','display_order','is_active']], 'posts'=>['table'=>'blog_posts','title'=>'Blog posts','fields'=>['title','slug','excerpt','body','status','published_at']], 'categories'=>['table'=>'categories','title'=>'Categories','fields'=>['name','slug']], 'genres'=>['table'=>'genres','title'=>'Genres','fields'=>['name','slug']], 'settings'=>['table'=>'settings','title'=>'Homepage settings','fields'=>['setting_key','setting_value']], 'coupons'=>['table'=>'coupons','title'=>'Coupons','fields'=>['code','discount_type','discount_value','starts_at','ends_at','is_active']], 'reviews'=>['table'=>'reviews','title'=>'Reviews','fields'=>['rating','body','status'],'creatable'=>false], 'contacts'=>['table'=>'contact_messages','title'=>'Contact messages','fields'=>['name','email','subject','message','status']], 'quotes'=>['table'=>'quote_requests','title'=>'Quote requests','fields'=>['name','email','phone','book_title','description','status']]];
    public function dashboard(): never {$this->requireAdmin();$stats=[];foreach(['orders','customers','books','authors','downloads','quote_requests','contact_messages','newsletter_subscribers'] as $table){$stats[$table]=(int)($this->one("SELECT COUNT(*) count FROM $table")['count']??0);} $revenue=(float)($this->one("SELECT COALESCE(SUM(total),0) total FROM orders WHERE payment_status='paid'")['total']??0);$recent=$this->all('SELECT * FROM orders ORDER BY created_at DESC LIMIT 6');$this->render('admin/dashboard',compact('stats','revenue','recent'));}
    public function bookFiles(): never {$this->requireAdmin();$books=$this->all('SELECT id,title FROM books ORDER BY title');$files=$this->all('SELECT bf.*,b.title FROM book_files bf JOIN books b ON b.id=bf.book_id ORDER BY bf.created_at DESC');$this->render('admin/book-files',compact('books','files'));}
    public function uploadBookFile(): never {$this->requireAdmin();$this->requirePost();$bookId=(int)($_POST['book_id']??0);$book=$this->one('SELECT id FROM books WHERE id=?',[$bookId]);$file=$_FILES['file']??null;if(!$book||!$file||$file['error']!==UPLOAD_ERR_OK){Security::flash('error','Choose a valid book and upload file.');Security::redirect('/admin/book-files');}$extension=strtolower(pathinfo($file['name'],PATHINFO_EXTENSION));$allowed=['pdf'=>['application/pdf'],'epub'=>['application/epub+zip','application/zip']];$max=(int)(\App\Core\Env::get('MAX_BOOK_FILE_MB','100'))*1024*1024;$mime=(new \finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']);if(!isset($allowed[$extension])||!in_array($mime,$allowed[$extension],true)||$file['size']>$max){Security::flash('error','Only PDF or EPUB files within the configured size limit are accepted.');Security::redirect('/admin/book-files');}$stored=bin2hex(random_bytes(24)).'.'.$extension;$target=dirname(__DIR__,2).'/private/books/'.$stored;if(!move_uploaded_file($file['tmp_name'],$target)){Security::flash('error','The eBook could not be saved to private storage.');Security::redirect('/admin/book-files');}$this->db()->prepare('INSERT INTO book_files(book_id,format,storage_name,original_name,file_size) VALUES(?,?,?,?,?)')->execute([$bookId,$extension,$stored,basename($file['name']),$file['size']]);Security::flash('success','The eBook file is protected in private storage.');Security::redirect('/admin/book-files');}
    public function deleteBookFile(): never {$this->requireAdmin();$this->requirePost();$id=(int)($_POST['id']??0);$file=$this->one('SELECT * FROM book_files WHERE id=?',[$id]);if(!$file){Security::flash('error','File record not found.');Security::redirect('/admin/book-files');}$base=realpath(dirname(__DIR__,2).'/private/books');$path=$base?realpath($base.'/'.$file['storage_name']):false;if($path&&str_starts_with($path,$base.DIRECTORY_SEPARATOR))unlink($path);$this->db()->prepare('DELETE FROM book_files WHERE id=?')->execute([$id]);Security::flash('success','Protected eBook file removed.');Security::redirect('/admin/book-files');}
    public function export(string $kind): never {$this->requireAdmin();$map=['quotes'=>['quote_requests',['name','email','phone','book_title','genre','word_count','project_stage','budget_range','status','created_at']],'contacts'=>['contact_messages',['name','email','phone','subject','message','status','created_at']],'subscribers'=>['newsletter_subscribers',['email','status','consented_at','created_at']]];$spec=$map[$kind]??null;if(!$spec)$this->render('errors/404',[],404);$rows=$this->all('SELECT '.implode(',',$spec[1]).' FROM '.$spec[0].' ORDER BY id DESC');header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="archon-'.$kind.'-'.date('Ymd').'.csv"');$out=fopen('php://output','w');fputcsv($out,$spec[1]);foreach($rows as $row)fputcsv($out,$row);fclose($out);exit;}
    public function resource(string $name): never {$this->requireAdmin();$cfg=$this->resources[$name]??null;if(!$cfg)$this->render('errors/404',[],404);$q=trim($_GET['q']??'');$sql='SELECT * FROM '.$cfg['table'];$params=[];if($q!==''&&in_array('title',$cfg['fields'],true)){$sql.=' WHERE title LIKE ?';$params=['%'.$q.'%'];}$rows=$this->all($sql.' ORDER BY id DESC LIMIT 100',$params);$this->render('admin/resource',compact('cfg','name','rows'));}
    public function mutate(string $name,string $action): never {$this->requireAdmin();$this->requirePost();$cfg=$this->resources[$name]??null;if(!$cfg)$this->render('errors/404',[],404);$id=(int)($_POST['id']??0);if($action==='delete'){$this->db()->prepare('DELETE FROM '.$cfg['table'].' WHERE id=?')->execute([$id]);Security::flash('success','Record removed.');Security::redirect('/admin/'.$name);} $data=[];foreach($cfg['fields'] as $field){if(array_key_exists($field,$_POST))$data[$field]=is_string($_POST[$field])?trim($_POST[$field]):$_POST[$field];}if($cfg['table']==='books'&&empty($data['published_at']))$data['published_at']=date('Y-m-d');if(!$data){Security::flash('error','No values supplied.');Security::redirect('/admin/'.$name);}if($action==='create'){$keys=array_keys($data);$this->db()->prepare('INSERT INTO '.$cfg['table'].' ('.implode(',',$keys).') VALUES ('.implode(',',array_fill(0,count($keys),'?')).')')->execute(array_values($data));}else{$set=implode(',',array_map(fn($k)=>"$k=?",array_keys($data)));$this->db()->prepare('UPDATE '.$cfg['table']." SET $set WHERE id=?")->execute([...array_values($data),$id]);}Security::flash('success','Record saved.');Security::redirect('/admin/'.$name);}
}
