<?php
namespace App\Controllers;
use App\Core\Security;
use App\Services\MailService;
use App\Services\CartService;

final class ShopController extends Controller {
    private function cartItems(): array { return $_SESSION['cart'] ?? []; }
    private function coupon(float $subtotal): ?array { $code=strtoupper(trim($_SESSION['coupon']??''));if(!$code)return null;$coupon=$this->one('SELECT * FROM coupons WHERE code=? AND is_active=1 AND (starts_at IS NULL OR starts_at<=NOW()) AND (ends_at IS NULL OR ends_at>=NOW()) AND (max_uses IS NULL OR uses_count<max_uses)',[$code]);if(!$coupon){unset($_SESSION['coupon']);return null;}$discount=$coupon['discount_type']==='percent'?$subtotal*((float)$coupon['discount_value']/100):(float)$coupon['discount_value'];$coupon['discount']=min($subtotal,round($discount,2));return $coupon;}
    public function catalogue(): never {
        $q=trim($_GET['q']??'');$category=(int)($_GET['category']??0);$genre=(int)($_GET['genre']??0);$author=(int)($_GET['author']??0);$language=trim($_GET['language']??'');$free=!empty($_GET['free']);$sale=!empty($_GET['sale']);$min=$_GET['min']??'';$max=$_GET['max']??'';$sort=$_GET['sort']??'newest';$page=max(1,(int)($_GET['page']??1));$per=9;
        $where=['b.is_active=1'];$params=[];
        if($q!==''){$where[]='(b.title LIKE ? OR b.isbn LIKE ? OR a.name LIKE ?)';$params=array_merge($params,["%$q%","%$q%","%$q%"]);}
        if($author){$where[]='b.author_id=?';$params[]=$author;}if($category){$where[]='EXISTS(SELECT 1 FROM book_categories bc WHERE bc.book_id=b.id AND bc.category_id=?)';$params[]=$category;}if($genre){$where[]='EXISTS(SELECT 1 FROM book_genres bg WHERE bg.book_id=b.id AND bg.genre_id=?)';$params[]=$genre;}if($language!==''){$where[]='b.language=?';$params[]=$language;}if($free)$where[]='COALESCE(b.sale_price,b.price)=0';if($sale)$where[]='b.sale_price IS NOT NULL AND b.sale_price<b.price';if($min!==''){$where[]='COALESCE(b.sale_price,b.price)>=?';$params[]=(float)$min;}if($max!==''){$where[]='COALESCE(b.sale_price,b.price)<=?';$params[]=(float)$max;}
        $order=['price'=>'COALESCE(b.sale_price,b.price) ASC','rating'=>'b.rating DESC','popular'=>'b.sales_count DESC','newest'=>'b.published_at DESC'];$w=implode(' AND ',$where);$count=(int)($this->one("SELECT COUNT(*) total FROM books b JOIN authors a ON a.id=b.author_id WHERE $w",$params)['total']??0);$sql="SELECT b.*,a.name author_name FROM books b JOIN authors a ON a.id=b.author_id WHERE $w ORDER BY ".($order[$sort]??$order['newest'])." LIMIT $per OFFSET ".(($page-1)*$per);$books=$this->all($sql,$params);$categories=$this->all('SELECT * FROM categories ORDER BY name');$genres=$this->all('SELECT * FROM genres ORDER BY name');$authors=$this->all('SELECT id,name FROM authors WHERE is_active=1 ORDER BY name');$languages=$this->all('SELECT DISTINCT language FROM books WHERE is_active=1 ORDER BY language');$pages=max(1,(int)ceil($count/$per));$this->render('shop/catalogue',compact('books','categories','genres','authors','languages','q','category','genre','author','language','free','sale','min','max','sort','page','pages','count'));
    }
    public function book(string $slug): never { $book=$this->one('SELECT b.*,a.name author_name,a.slug author_slug,a.bio author_bio FROM books b JOIN authors a ON a.id=b.author_id WHERE b.slug=? AND b.is_active=1',[$slug]);if(!$book)$this->render('errors/404',[],404);$related=$this->all('SELECT b.*,a.name author_name FROM books b JOIN authors a ON a.id=b.author_id WHERE b.id<>? AND b.is_active=1 ORDER BY b.is_featured DESC LIMIT 3',[$book['id']]);$reviews=$this->all("SELECT r.*,c.name customer_name FROM reviews r JOIN customers c ON c.id=r.customer_id WHERE r.book_id=? AND r.status='approved' ORDER BY r.created_at DESC",[$book['id']]);$canReview=false;if($this->customer())$canReview=(bool)$this->one("SELECT oi.id FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE oi.book_id=? AND o.customer_id=? AND o.payment_status='paid' LIMIT 1",[$book['id'],$this->customer()['id']]);$this->render('shop/book',compact('book','related','reviews','canReview')); }
    public function submitReview(string $slug): never {$this->requirePost();$customer=$this->requireCustomer();if(!Security::rateLimit('review',5,3600)){Security::flash('error','Please wait before submitting another review.');Security::redirect('/ebooks/'.$slug);}$book=$this->one('SELECT id FROM books WHERE slug=? AND is_active=1',[$slug]);if(!$book){Security::redirect('/ebooks');}$owned=$this->one("SELECT oi.id FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE oi.book_id=? AND o.customer_id=? AND o.payment_status='paid' LIMIT 1",[$book['id'],$customer['id']]);$rating=(int)($_POST['rating']??0);$body=trim($_POST['body']??'');if(!$owned||$rating<1||$rating>5||strlen($body)<15||strlen($body)>2000){Security::flash('error','Reviews require a completed purchase, a 1–5 rating, and 15–2,000 characters.');Security::redirect('/ebooks/'.$slug);}$existing=$this->one('SELECT id FROM reviews WHERE customer_id=? AND book_id=?',[$customer['id'],$book['id']]);if($existing)$this->db()->prepare("UPDATE reviews SET rating=?,body=?,status='pending',updated_at=NOW() WHERE id=?")->execute([$rating,$body,$existing['id']]);else $this->db()->prepare("INSERT INTO reviews(customer_id,book_id,rating,body,status) VALUES(?,?,?,?,'pending')")->execute([$customer['id'],$book['id'],$rating,$body]);Security::flash('success','Thank you. Your review is awaiting moderation.');Security::redirect('/ebooks/'.$slug);}
    public function cart(): never { $ids=array_keys($this->cartItems());$books=[];if($ids){$marks=implode(',',array_fill(0,count($ids),'?'));$books=$this->all("SELECT b.*,a.name author_name FROM books b JOIN authors a ON a.id=b.author_id WHERE b.id IN($marks)",$ids);} $subtotal=array_sum(array_map(fn($b)=>(float)($b['sale_price']?:$b['price']),$books));$coupon=$this->coupon($subtotal);$discount=(float)($coupon['discount']??0);$total=$subtotal-$discount;$this->render('shop/cart',compact('books','subtotal','coupon','discount','total')); }
    public function add(): never { $this->requirePost();$id=(int)($_POST['book_id']??0);$book=$this->one('SELECT id FROM books WHERE id=? AND is_active=1',[$id]);if(!$book){Security::flash('error','This eBook is not currently available.');Security::redirect('/ebooks');}$_SESSION['cart'][$id]=1;if($this->customer())CartService::add((int)$this->customer()['id'],$id);Security::flash('success','eBook added to your reading cart.');Security::redirect($_POST['return_to']??'/cart'); }
    public function remove(): never {$this->requirePost();$id=(int)($_POST['book_id']??0);unset($_SESSION['cart'][$id]);if($this->customer())CartService::remove((int)$this->customer()['id'],$id);Security::flash('success','Item removed from your cart.');Security::redirect('/cart');}
    public function applyCoupon(): never {$this->requirePost();$code=strtoupper(trim($_POST['code']??''));if(!preg_match('/^[A-Z0-9-]{3,50}$/',$code)){Security::flash('error','Enter a valid coupon code.');Security::redirect('/cart');}$_SESSION['coupon']=$code;Security::flash('success','Coupon applied if it is currently valid.');Security::redirect('/cart');}
    public function removeCoupon(): never {$this->requirePost();unset($_SESSION['coupon']);Security::flash('success','Coupon removed.');Security::redirect('/cart');}
    public function checkout(): never { $this->requireCustomer();$ids=array_keys($this->cartItems());if(!$ids){Security::flash('error','Your cart is empty.');Security::redirect('/ebooks');}$marks=implode(',',array_fill(0,count($ids),'?'));$books=$this->all("SELECT b.*,a.name author_name FROM books b JOIN authors a ON a.id=b.author_id WHERE b.id IN($marks) AND b.is_active=1",$ids);$subtotal=array_sum(array_map(fn($b)=>(float)($b['sale_price']?:$b['price']),$books));$coupon=$this->coupon($subtotal);$discount=(float)($coupon['discount']??0);$total=$subtotal-$discount;$this->render('shop/checkout',compact('books','subtotal','coupon','discount','total')); }
    public function placeOrder(): never { $this->requirePost();$customer=$this->requireCustomer();$ids=array_keys($this->cartItems());if(!$ids){Security::flash('error','Your cart is empty.');Security::redirect('/ebooks');}$marks=implode(',',array_fill(0,count($ids),'?'));$pdo=$this->db();$pdo->beginTransaction();try{$books=$this->all("SELECT * FROM books WHERE id IN($marks) AND is_active=1 FOR UPDATE",$ids);if(count($books)!==count($ids))throw new \RuntimeException('A selected title is unavailable.');$subtotal=array_sum(array_map(fn($b)=>(float)($b['sale_price']?:$b['price']),$books));$coupon=$this->coupon($subtotal);$discount=(float)($coupon['discount']??0);$tax=0;$total=$subtotal-$discount+$tax;$number='ARC-'.date('Ymd').'-'.strtoupper(bin2hex(random_bytes(3)));$method=$_POST['payment_method']==='bank'?'bank_transfer':'demo';$paymentStatus=$method==='demo'?'paid':'pending';$orderStatus=$method==='demo'?'completed':'pending_payment';$pdo->prepare('INSERT INTO orders (order_number,customer_id,subtotal,discount_amount,tax_amount,total,currency,payment_status,order_status,payment_method) VALUES (?,?,?,?,?,?,?,?,?,?)')->execute([$number,$customer['id'],$subtotal,$discount,$tax,$total,'USD',$paymentStatus,$orderStatus,$method]);$order=(int)$pdo->lastInsertId();$line=$pdo->prepare('INSERT INTO order_items (order_id,book_id,title,unit_price) VALUES (?,?,?,?)');$download=$pdo->prepare('INSERT INTO downloads (order_item_id,customer_id,token,expires_at,max_count) VALUES (?,?,?,?,5)');foreach($books as $book){$price=$book['sale_price']?:$book['price'];$line->execute([$order,$book['id'],$book['title'],$price]);$item=(int)$pdo->lastInsertId();if($paymentStatus==='paid')$download->execute([$item,$customer['id'],bin2hex(random_bytes(16)),date('Y-m-d H:i:s',time()+1800)]);}if($coupon){$pdo->prepare('UPDATE coupons SET uses_count=uses_count+1 WHERE id=?')->execute([$coupon['id']]);$pdo->prepare('INSERT INTO coupon_uses(coupon_id,customer_id,order_id) VALUES(?,?,?)')->execute([$coupon['id'],$customer['id'],$order]);}$pdo->prepare('INSERT INTO payments (order_id,amount,status,method,reference) VALUES (?,?,?,?,?)')->execute([$order,$total,$paymentStatus,$method,$number]);$pdo->commit();CartService::clear((int)$customer['id']);unset($_SESSION['cart'],$_SESSION['coupon']);MailService::send($customer['email'],'Archon order '.$number,$method==='demo'?'Your payment was approved in demo mode. Sign in to access your eBooks.':'Your order is pending bank-transfer confirmation.');Security::flash('success',$method==='demo'?'Payment approved in safe demo mode. Your downloads are ready.':'Order created. Follow the bank-transfer instructions sent by email.');Security::redirect('/account');}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();Security::flash('error','Checkout could not be completed. Please review your cart and try again.');Security::redirect('/checkout');}}
}
